apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-service-config
  namespace: ${K8S_NAMESPACE}
data:
  NODE_ENV: "production"
  PORT: "3002"
  LOG_LEVEL: "info"
  AWS_REGION: ${AWS_REGION}
  AWS_ELASTICACHE_PORT: "6379"
  DD_AGENT_HOST: "datadog-agent"
  DD_TRACE_AGENT_PORT: "8126"
  DD_LOGS_ENABLED: "true"
  DD_APM_ENABLED: "true"
  DD_RUNTIME_METRICS_ENABLED: "true" 