apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: cache-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
        - name: cache-service
          image: ${ECR_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: cache-service-config
            - secretRef:
                name: cache-service-secrets 