apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: ${K8S_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: cache-service 